return {
-- libusb_class_code 
LIBUSB_CLASS_PER_INTERFACE = 0,
LIBUSB_CLASS_AUDIO = 1,
LIBUSB_CLASS_COMM = 2,
LIBUSB_CLASS_HID = 3,
LIBUSB_CLASS_PHYSICAL = 5,
LIBUSB_CLASS_PRINTER = 7,
LIBUSB_CLASS_PTP = 6,
LIBUSB_CLASS_IMAGE = 6,
LIBUSB_CLASS_MASS_STORAGE = 8,
LIBUSB_CLASS_HUB = 9,
LIBUSB_CLASS_DATA = 10,
LIBUSB_CLASS_SMART_CARD = 0x0b,
LIBUSB_CLASS_CONTENT_SECURITY = 0x0d,
LIBUSB_CLASS_VIDEO = 0x0e,
LIBUSB_CLASS_PERSONAL_HEALTHCARE = 0x0f,
LIBUSB_CLASS_DIAGNOSTIC_DEVICE = 0xdc,
LIBUSB_CLASS_WIRELESS = 0xe0,
LIBUSB_CLASS_APPLICATION = 0xfe,
LIBUSB_CLASS_VENDOR_SPEC = 0xff,

-- libusb_descriptor_type 
LIBUSB_DT_DEVICE = 0x01,
LIBUSB_DT_CONFIG = 0x02,
LIBUSB_DT_STRING = 0x03,
LIBUSB_DT_INTERFACE = 0x04,
LIBUSB_DT_ENDPOINT = 0x05,
LIBUSB_DT_HID = 0x21,
LIBUSB_DT_REPORT = 0x22,
LIBUSB_DT_PHYSICAL = 0x23,
LIBUSB_DT_HUB = 0x29,

-- libusb_endpoint_direction 
LIBUSB_ENDPOINT_IN = 0x80,
LIBUSB_ENDPOINT_OUT = 0x00,

-- libusb_transfer_type 
LIBUSB_TRANSFER_TYPE_CONTROL = 0,
LIBUSB_TRANSFER_TYPE_ISOCHRONOUS = 1,
LIBUSB_TRANSFER_TYPE_BULK = 2,
LIBUSB_TRANSFER_TYPE_INTERRUPT = 3,

-- libusb_standard_request 
LIBUSB_REQUEST_GET_STATUS = 0x00,
LIBUSB_REQUEST_CLEAR_FEATURE = 0x01,
LIBUSB_REQUEST_SET_FEATURE = 0x03,
LIBUSB_REQUEST_SET_ADDRESS = 0x05,
LIBUSB_REQUEST_GET_DESCRIPTOR = 0x06,
LIBUSB_REQUEST_SET_DESCRIPTOR = 0x07,
LIBUSB_REQUEST_GET_CONFIGURATION = 0x08,
LIBUSB_REQUEST_SET_CONFIGURATION = 0x09,
LIBUSB_REQUEST_GET_INTERFACE = 0x0A,
LIBUSB_REQUEST_SET_INTERFACE = 0x0B,
LIBUSB_REQUEST_SYNCH_FRAME = 0x0C,

-- libusb_request_type 
LIBUSB_REQUEST_TYPE_STANDARD = bit.lshift(0x00, 5),
LIBUSB_REQUEST_TYPE_CLASS = bit.lshift(0x01, 5),
LIBUSB_REQUEST_TYPE_VENDOR = bit.lshift(0x02, 5),
LIBUSB_REQUEST_TYPE_RESERVED = bit.lshift(0x03, 5),

-- libusb_request_recipient 
LIBUSB_RECIPIENT_DEVICE = 0x00,
LIBUSB_RECIPIENT_INTERFACE = 0x01,
LIBUSB_RECIPIENT_ENDPOINT = 0x02,
LIBUSB_RECIPIENT_OTHER = 0x03,

-- libusb_iso_sync_type 
LIBUSB_ISO_SYNC_TYPE_NONE = 0,
LIBUSB_ISO_SYNC_TYPE_ASYNC = 1,
LIBUSB_ISO_SYNC_TYPE_ADAPTIVE = 2,
LIBUSB_ISO_SYNC_TYPE_SYNC = 3,

-- libusb_iso_usage_type 
LIBUSB_ISO_USAGE_TYPE_DATA = 0,
LIBUSB_ISO_USAGE_TYPE_FEEDBACK = 1,
LIBUSB_ISO_USAGE_TYPE_IMPLICIT = 2,

-- libusb_speed 
LIBUSB_SPEED_UNKNOWN = 0,
LIBUSB_SPEED_LOW = 1,
LIBUSB_SPEED_FULL = 2,
LIBUSB_SPEED_HIGH = 3,
LIBUSB_SPEED_SUPER = 4,

-- libusb_error 
LIBUSB_SUCCESS = 0,
LIBUSB_ERROR_IO = -1,
LIBUSB_ERROR_INVALID_PARAM = -2,
LIBUSB_ERROR_ACCESS = -3,
LIBUSB_ERROR_NO_DEVICE = -4,
LIBUSB_ERROR_NOT_FOUND = -5,
LIBUSB_ERROR_BUSY = -6,
LIBUSB_ERROR_TIMEOUT = -7,
LIBUSB_ERROR_OVERFLOW = -8,
LIBUSB_ERROR_PIPE = -9,
LIBUSB_ERROR_INTERRUPTED = -10,
LIBUSB_ERROR_NO_MEM = -11,
LIBUSB_ERROR_NOT_SUPPORTED = -12,
LIBUSB_ERROR_OTHER = -99,

-- libusb_transfer_status 
LIBUSB_TRANSFER_COMPLETED = 1,
LIBUSB_TRANSFER_ERROR = 2,
LIBUSB_TRANSFER_TIMED_OUT = 3,
LIBUSB_TRANSFER_CANCELLED = 4,
LIBUSB_TRANSFER_STALL = 5,
LIBUSB_TRANSFER_NO_DEVICE = 6,
LIBUSB_TRANSFER_OVERFLOW = 7,

-- libusb_transfer_flags 
LIBUSB_TRANSFER_SHORT_NOT_OK = bit.lshift(1, 0),
LIBUSB_TRANSFER_FREE_BUFFER = bit.lshift(1, 1),
LIBUSB_TRANSFER_FREE_TRANSFER = bit.lshift(1, 2),
LIBUSB_TRANSFER_ADD_ZERO_PACKET = bit.lshift(1, 3),

-- libusb_capability
LIBUSB_CAP_HAS_CAPABILITY = 0,
}