local gmod = ... or gmod
local env = gmod.env

env.SENSORBONE = {}
local SENSORBONE = env.SENSORBONE

SENSORBONE.SHOULDER_RIGHT = 8
SENSORBONE.SHOULDER_LEFT = 4
SENSORBONE.HIP = 0
SENSORBONE.ELBOW_RIGHT = 9
SENSORBONE.KNEE_RIGHT = 17
SENSORBONE.WRIST_RIGHT = 10
SENSORBONE.ANKLE_LEFT = 14
SENSORBONE.FOOT_LEFT = 15
SENSORBONE.WRIST_LEFT = 6
SENSORBONE.FOOT_RIGHT = 19
SENSORBONE.HAND_RIGHT = 11
SENSORBONE.SHOULDER = 2
SENSORBONE.HIP_LEFT = 12
SENSORBONE.HIP_RIGHT = 16
SENSORBONE.HAND_LEFT = 7
SENSORBONE.ANKLE_RIGHT = 18
SENSORBONE.SPINE = 1
SENSORBONE.ELBOW_LEFT = 5
SENSORBONE.KNEE_LEFT = 13
SENSORBONE.HEAD = 3