local META = {}

META.Type = "Entity"

function META:SetLOD() end
function META:IsNPC() end
function META:GetNWEntity() end
function META:SetNotSolid() end
function META:SetShouldServerRagdoll() end
function META:SetNetworkAngles() end
function META:SetPos() end
function META:SetTransmitWithParent() end
function META:MarkShadowAsDirty() end
function META:GetManipulateBonePosition() end
function META:SetAnimation() end
function META:SetCollisionBoundsWS() end
function META:HasBoneManipulations() end
function META:GetDTInt() end
function META:PhysicsInitSphere() end
function META:GetHitBoxBounds() end
function META:Spawn() end
function META:GetNumPoseParameters() end
function META:SetDTInt() end
function META:SetBoneController() end
function META:WorldSpaceAABB() end
function META:GibBreakClient() end
function META:GetClass() end
function META:GetLocalAngularVelocity() end
function META:GetRight() end
function META:ClearPoseParameters() end
function META:SetNetworkedEntity() end
function META:SetCustomCollisionCheck() end
function META:GetLocalAngles() end
function META:GetModelBounds() end
function META:GetSkin() end
function META:AddCallback() end
function META:GetFlexBounds() end
function META:ManipulateBoneJiggle() end
function META:SetSaveValue() end
function META:AddFlags() end
function META:GetCustomCollisionCheck() end
function META:ResetSequenceInfo() end
function META:GetPlaybackRate() end
function META:GibBreakServer() end
function META:OBBMins() end
function META:FireBullets() end
function META:GetBoneController() end
function META:GetAngles() end
function META:GetSequenceInfo() end
function META:GetDTString() end
function META:TranslatePhysBoneToBone() end
function META:EmitSound() end
function META:GetFlexScale() end
function META:GetDTEntity() end
function META:SetEntity() end
function META:SetLocalAngularVelocity() end
function META:GetNetworkedVarTable() end
function META:SelectWeightedSequenceSeeded() end
function META:WorldToLocal() end
function META:__tostring() end
function META:StopParticleEmission() end
function META:ManipulateBoneAngles() end
function META:GetModelScale() end
function META:SetNetworkOrigin() end
function META:SetPersistent() end
function META:GetAttachments() end
function META:GetPersistent() end
function META:GetBoneCount() end
function META:SetModelScale() end
function META:PhysicsInitConvex() end
function META:FindTransitionSequence() end
function META:IsWorld() end
function META:StopLoopingSound() end
function META:SetLocalVelocity() end
function META:GetDTBool() end
function META:HasFlexManipulatior() end
function META:GetAbsVelocity() end
function META:GetShouldServerRagdoll() end
function META:SetPlaybackRate() end
function META:SetAttachment() end
function META:SetVelocity() end
function META:GetAttachment() end
function META:GetNetworkedString() end
function META:GetForward() end
function META:SetNetworkedInt() end
function META:PhysicsDestroy() end
function META:SetAbsVelocity() end
function META:GetBodygroup() end
function META:RemoveEffects() end
function META:BecomeRagdollOnClient() end
function META:GetBoneMatrix() end
function META:DestroyShadow() end
function META:GetParent() end
function META:GetCollisionGroup() end
function META:SetWeaponModel() end
function META:RestartGesture() end
function META:SetBoneMatrix() end
function META:SetNoDraw() end
function META:GetBrushPlane() end
function META:GetNoDraw() end
function META:Activate() end
function META:GetInternalVariable() end
function META:GetMoveCollide() end
function META:SetNWEntity() end
function META:SetCollisionGroup() end
function META:FollowBone() end
function META:GetSpawnEffect() end
function META:IsPlayer() end
function META:ForcePlayerDrop() end
function META:GetUp() end
function META:PhysicsInit() end
function META:SetNetworkedBool() end
function META:SetParent() end
function META:SetNetworkedVector() end
function META:GetSubModels() end
function META:IsRagdoll() end
function META:IsEffectActive() end
function META:LocalToWorldAngles() end
function META:GetSequenceActivity() end
function META:GetNWVarTable() end
function META:SetEyeTarget() end
function META:SetIK() end
function META:GetPoseParameterName() end
function META:GetFlexWeight() end
function META:SetBodygroup() end
function META:AlignAngles() end
function META:AddEffects() end
function META:EntIndex() end
function META:SetFlexWeight() end
function META:SetRenderMode() end
function META:SetDTEntity() end
function META:SetOwner() end
function META:GetModelRadius() end
function META:LookupSequence() end
function META:IsLineOfSightClear() end
function META:GPO() end
function META:WaterLevel() end
function META:BoneHasFlag() end
function META:GetDTAngle() end
function META:GetRenderMode() end
function META:GetRenderFX() end
function META:GetBodygroupCount() end
function META:GetMoveParent() end
function META:LookupAttachment() end
function META:SetRenderFX() end
function META:SetFlexScale() end
function META:GetOwner() end
function META:SetRenderBoundsWS() end
function META:GetNWAngle() end
function META:GetManipulateBoneAngles() end
function META:SelectWeightedSequence() end
function META:NextThink() end
function META:SetMoveParent() end
function META:SetPoseParameter() end
function META:SetSpawnEffect() end
function META:OnGround() end
function META:GetAnimInfo() end
function META:SetMoveType() end
function META:SetupBones() end
function META:GetMoveType() end
function META:GetModelPhysBoneCount() end
function META:GetHitboxSet() end
function META:GetGravity() end
function META:GetModelRenderBounds() end
function META:GetSolid() end
function META:RemoveEFlags() end
function META:SetLegacyTransform() end
function META:InvalidateBoneCache() end
function META:GetSequenceName() end
function META:EnableMatrix() end
function META:SetMaterial() end
function META:Health() end
function META:SetNextClientThink() end
function META:GetPos() end
function META:__concat() end
function META:CreateParticleEffect() end
function META:CreateShadow() end
function META:IsOnFire() end
function META:ObjectCaps() end
function META:GetRenderGroup() end
function META:PhysicsInitShadow() end
function META:GetHitboxSetCount() end
function META:SetRenderClipPlaneEnabled() end
function META:SetAnimTime() end
function META:SetRenderBounds() end
function META:GetElasticity() end
function META:GetRenderBounds() end
function META:DisableMatrix() end
function META:BoneLength() end
function META:GetFlexNum() end
function META:DrawModel() end
function META:InitializeAsClientEntity() end
function META:SetBonePosition() end
function META:SetHitboxSet() end
function META:GetHitBoxCount() end
function META:UseTriggerBounds() end
function META:GetAnimTime() end
function META:PhysicsFromMesh() end
function META:OBBCenter() end
function META:SetRenderClipPlane() end
function META:GetNetworkedEntity() end
function META:SetDTAngle() end
function META:DrawShadow() end
function META:SetNWAngle() end
function META:SetSolid() end
function META:NearestPoint() end
function META:GetNetworkOrigin() end
function META:GetCreationTime() end
function META:AddEFlags() end
function META:GetPhysicsObjectNum() end
function META:GetNWVector() end
function META:SetNWVector() end
function META:GetNetworkedVector() end
function META:SetFriction() end
function META:GetSequenceActivityName() end
function META:GetTouchTrace() end
function META:GetDTFloat() end
function META:StopSound() end
function META:SetNetworkedString() end
function META:GetSequenceGroundSpeed() end
function META:GetBodyGroups() end
function META:GetNetworkedBool() end
function META:GetMaterials() end
function META:ManipulateBonePosition() end
function META:StopMotionController() end
function META:GetNWFloat() end
function META:SetNWFloat() end
function META:GetNetworkedFloat() end
function META:SetNetworkedFloat() end
function META:GetNWInt() end
function META:SetBodyGroups() end
function META:SetNWInt() end
function META:GetNetworkedInt() end
function META:ResetSequence() end
function META:IsSolid() end
function META:IsDormant() end
function META:GetDTVector() end
function META:FrameAdvance() end
function META:WorldSpaceCenter() end
function META:GetRagdollOwner() end
function META:UseClientSideAnimation() end
function META:SetModelName() end
function META:__eq() end
function META:TranslateBoneToPhysBone() end
function META:SetupPhonemeMappings() end
function META:GetFriction() end
function META:SkinCount() end
function META:GetSequenceCount() end
function META:ViewModelIndex() end
function META:MakePhysicsObjectAShadow() end
function META:BoundingRadius() end
function META:GetRotatedAABB() end
function META:SendViewModelMatchingSequence() end
function META:IsValid() end
function META:RemoveFlags() end
function META:SetLocalPos() end
function META:GetCollisionBounds() end
function META:EnableCustomCollisions() end
function META:Weapon_TranslateActivity() end
function META:OBBMaxs() end
function META:GetManipulateBoneJiggle() end
function META:GetPoseParameterRange() end
function META:SetGroundEntity() end
function META:SetSkin() end
function META:SetCycle() end
function META:ManipulateBoneScale() end
function META:SetCollisionBounds() end
function META:__newindex() end
function META:IsEFlagSet() end
function META:GetVelocity() end
function META:SetColor() end
function META:SetModel() end
function META:GetParentAttachment() end
function META:GetParentPhysNum() end
function META:LocalToWorld() end
function META:SetDTBool() end
function META:GetNetworkAngles() end
function META:SetParentPhysNum() end
function META:SetDTVector() end
function META:Weapon_SetActivity() end
function META:StartLoopingSound() end
function META:SetNetworkedAngle() end
function META:GetManipulateBoneScale() end
function META:GetCycle() end
function META:GetBrushPlaneCount() end
function META:GetMaterial() end
function META:GetBonePosition() end
function META:GetPhysicsObjectCount() end
function META:GetModel() end
function META:EyePos() end
function META:GetNetworkedAngle() end
function META:GetSaveTable() end
function META:GetHitBoxGroupCount() end
function META:GetFlexName() end
function META:GetGroundEntity() end
function META:SetHealth() end
function META:PhysicsInitMultiConvex() end
function META:HasSpawnFlags() end
function META:GetBoneName() end
function META:SetElasticity() end
function META:GetColor() end
function META:LookupBone() end
function META:GetLocalPos() end
function META:IsWeapon() end
function META:IsVehicle() end
function META:GetMaxHealth() end
function META:GetNumBodyGroups() end
function META:PhysicsInitBox() end
function META:GetTransmitWithParent() end
function META:StopParticles() end
function META:EyeAngles() end
function META:GetSubMaterial() end
function META:GetHitBoxBone() end
function META:SetPredictable() end
function META:SequenceDuration() end
function META:GetSpawnFlags() end
function META:GetSequence() end
function META:SetDTString() end
function META:SetSequence() end
function META:StartMotionController() end
function META:DispatchTraceAttack() end
function META:GetTable() end
function META:IsOnGround() end
function META:GetPoseParameter() end
function META:RemoveAllDecals() end
function META:SetGravity() end
function META:IsFlagSet() end
function META:SetKeyValue() end
function META:SetSubMaterial() end
function META:MuzzleFlash() end
function META:GetSequenceList() end
function META:GetBodygroupName() end
function META:SetAngles() end
function META:WorldToLocalAngles() end
function META:FindBodygroupByName() end
function META:SetDTFloat() end
function META:SetLocalAngles() end
function META:GetBoneParent() end
function META:SetTable() end

return META