local META = {}

META.Type = "Panel"

function META:CursorPos() end
function META:GetPos() end
function META:IsLoading() end
function META:ParentToHUD() end
function META:GetDock() end
function META:SetPaintBorderEnabled() end
function META:SetTextInset() end
function META:KillFocus() end
function META:GotoTextEnd() end
function META:GetSize() end
function META:SizeToChildren() end
function META:SetMinimumSize() end
function META:__index() end
function META:SetRenderInScreenshots() end
function META:HasChildren() end
function META:DrawTextEntryText() end
function META:Refresh() end
function META:Remove() end
function META:IsMarkedForDeletion() end
function META:GetBounds() end
function META:SetSize() end
function META:SaveUndoState() end
function META:SetSteamID() end
function META:InsertClickableTextEnd() end
function META:SetAchievement() end
function META:IsMouseInputEnabled() end
function META:SetExpensiveShadow() end
function META:SetAutoDelete() end
function META:SetActionFunction() end
function META:Undo() end
function META:__tostring() end
function META:RebuildSpawnIconEx() end
function META:SetAlpha() end
function META:Prepare() end
function META:SetVisible() end
function META:DockPadding() end
function META:GetFont() end
function META:SetVerticalScrollbarEnabled() end
function META:DoModal() end
function META:PostMessage() end
function META:SetCursor() end
function META:SetMouseInputEnabled() end
function META:NewObject() end
function META:SetHTML() end
function META:InsertClickableTextStart() end
function META:InsertColorChange() end
function META:DrawOutlinedRect() end
function META:SetToFullHeight() end
function META:SelectAll() end
function META:GetName() end
function META:MoveToBack() end
function META:SetParent() end
function META:HasHierarchicalFocus() end
function META:HasParent() end
function META:SetPaintBackgroundEnabled() end
function META:GetHTMLMaterial() end
function META:MouseCapture() end
function META:GetChildren() end
function META:GetNumLines() end
function META:MakePopup() end
function META:SetWorldClicker() end
function META:SetURL() end
function META:LoadControlsFromString() end
function META:SizeToContents() end
function META:AddText() end
function META:SetSpawnIcon() end
function META:Find() end
function META:GotoTextStart() end
function META:SetTabPosition() end
function META:LocalToScreen() end
function META:__newindex() end
function META:IsKeyboardInputEnabled() end
function META:InsertFade() end
function META:SetText() end
function META:AppendText() end
function META:Valid() end
function META:GetTextInset() end
function META:GetValue() end
function META:OnMousePressed() end
function META:OpenURL() end
function META:RequestFocus() end
function META:IsMultiline() end
function META:LoadTGAImage() end
function META:GetTextSize() end
function META:IsVisible() end
function META:GetWide() end
function META:NewObjectCallback() end
function META:RebuildSpawnIcon() end
function META:IsValid() end
function META:SetAllowNonAsciiCharacters() end
function META:SetMultiline() end
function META:__gc() end
function META:GetTable() end
function META:SetPlayer() end
function META:SetEnabled() end
function META:DockMargin() end
function META:NoClipping() end
function META:SetDrawLanguageIDAtLeft() end
function META:SetName() end
function META:SetCommand() end
function META:DrawTexturedRect() end
function META:SetKeyboardInputEnabled() end
function META:GetClassName() end
function META:SetModel() end
function META:GetChild() end
function META:SetPos() end
function META:CopySelected() end
function META:RunJavascript() end
function META:SetKeyBoardInputEnabled() end
function META:PaintAt() end
function META:SetPopupStayAtBack() end
function META:FocusNext() end
function META:ScreenToLocal() end
function META:__eq() end
function META:SelectNone() end
function META:SetContentAlignment() end
function META:GetParent() end
function META:SetWrap() end
function META:DrawFilledRect() end
function META:Dock() end
function META:Paste() end
function META:SetBGColorEx() end
function META:SetPaintFunction() end
function META:GetContentSize() end
function META:ResetAllFades() end
function META:UpdateHTMLTexture() end
function META:Command() end
function META:PaintManual() end
function META:SetFocusTopLevel() end
function META:SetFGColorEx() end
function META:SelectAllText() end
function META:InvalidateLayout() end
function META:HasFocus() end
function META:SetDrawOnTop() end
function META:FocusPrevious() end
function META:GetAlpha() end
function META:CutSelected() end
function META:SetPaintedManually() end
function META:SetFontInternal() end
function META:GetCaretPos() end
function META:SetZPos() end
function META:GetText() end
function META:LoadControlsFromFile() end
function META:GetTall() end
function META:MoveToFront() end
function META:SetCaretPos() end
function META:ChildrenSize() end
function META:SelectAllOnFocus() end
function META:Exec() end
function META:ChildCount() end

return META