local META = {}

META.Type = "Player"

function META:VoiceVolume() end
function META:IsNPC() end
function META:Frags() end
function META:SetNoCollideWithTeammates() end
function META:FlashlightIsOn() end
function META:SetHoveredWidget() end
function META:DoSecondaryAttack() end
function META:GetActiveWeapon() end
function META:GetVehicle() end
function META:RealName() end
function META:SetStepSize() end
function META:GetFOV() end
function META:StartSprinting() end
function META:PacketLoss() end
function META:ViewPunchReset() end
function META:GetCurrentCommand() end
function META:GetPunchAngle() end
function META:Freeze() end
function META:GetStepSize() end
function META:GetAvoidPlayers() end
function META:GetViewOffsetDucked() end
function META:SetAllowFullRotation() end
function META:GetRenderAngles() end
function META:GetAllowFullRotation() end
function META:SetAvoidPlayers() end
function META:GetHoveredWidget() end
function META:GetViewOffset() end
function META:PrintMessage() end
function META:GetObserverTarget() end
function META:__tostring() end
function META:Crouching() end
function META:AnimRestartMainSequence() end
function META:SetWeaponColor() end
function META:GetCanWalk() end
function META:GetRagdollEntity() end
function META:SetCanWalk() end
function META:SetHull() end
function META:ChatPrint() end
function META:IsVehicle() end
function META:GetWeapon() end
function META:ViewPunch() end
function META:DoAttackEvent() end
function META:GetViewPunchAngles() end
function META:GetViewEntity() end
function META:SetMuted() end
function META:IsSpeaking() end
function META:StopSprinting() end
function META:AddVCDSequenceToGestureSlot() end
function META:SetViewOffsetDucked() end
function META:IsDrivingEntity() end
function META:IsPlayer() end
function META:SetDrivingEntity() end
function META:ShouldDrawLocalPlayer() end
function META:GetInfoNum() end
function META:ResetHull() end
function META:GetDrivingEntity() end
function META:GetUnDuckSpeed() end
function META:StopWalking() end
function META:IsMuted() end
function META:GetAimVector() end
function META:GetViewModel() end
function META:KeyReleased() end
function META:KeyPressed() end
function META:CommunityID() end
function META:Armor() end
function META:AnimSetGestureWeight() end
function META:LagCompensation() end
function META:GetShootPos() end
function META:Team() end
function META:Alive() end
function META:SetEyeAngles() end
function META:IsWorldClicking() end
function META:SetUnDuckSpeed() end
function META:StartWalking() end
function META:InVehicle() end
function META:SetDuckSpeed() end
function META:GetObserverMode() end
function META:SetMaxSpeed() end
function META:GetMaxSpeed() end
function META:__newindex() end
function META:SetCrouchedWalkSpeed() end
function META:IsWeapon() end
function META:TranslateWeaponActivity() end
function META:SetDSP() end
function META:KeyDownLast() end
function META:GetWeaponColor() end
function META:GetRunSpeed() end
function META:GetClassID() end
function META:SetAmmo() end
function META:SetClassID() end
function META:SetObserverMode() end
function META:DoCustomAnimEvent() end
function META:DoReloadEvent() end
function META:SetHullDuck() end
function META:KeyDown() end
function META:SetHands() end
function META:SetJumpPower() end
function META:GetCanZoom() end
function META:SteamID() end
function META:UserID() end
function META:RemoveAmmo() end
function META:IsVoiceAudible() end
function META:SetViewPunchAngles() end
function META:GetNoCollideWithTeammates() end
function META:IsPlayingTaunt() end
function META:GetWeapons() end
function META:IsBot() end
function META:GetFriendStatus() end
function META:SetPlayerColor() end
function META:GetInfo() end
function META:MotionSensorPos() end
function META:SetFOV() end
function META:SetViewOffset() end
function META:AnimResetGestureSlot() end
function META:HasWeapon() end
function META:GetPlayerColor() end
function META:GetWalkSpeed() end
function META:SetPressedWidget() end
function META:DoAnimationEvent() end
function META:DrawViewModel() end
function META:__gc() end
function META:IsSuitEquipped() end
function META:GetJumpPower() end
function META:GetCrouchedWalkSpeed() end
function META:SetRunSpeed() end
function META:ShowProfile() end
function META:SetWalkSpeed() end
function META:GetDrivingMode() end
function META:GetAllowWeaponsInVehicle() end
function META:GetAmmoCount() end
function META:GetCurrentViewOffset() end
function META:GetDuckSpeed() end
function META:GetPressedWidget() end
function META:AnimRestartGesture() end
function META:GetHands() end
function META:SetCurrentViewOffset() end
function META:GetPlayerInfo() end
function META:RemoveAllAmmo() end
function META:SetCanZoom() end
function META:SetRenderAngles() end
function META:Deaths() end

return META