local render = {}

function render.SuppressEngineLighting() end
function render.SetBlend() end
function render.SetStencilTestMask() end
function render.GetFullScreenDepthTexture() end
function render.DrawWireframeSphere() end
function render.FogMaxDensity() end
function render.DrawScreenQuadEx() end
function render.GetDXLevel() end
function render.GetSuperFPTex2() end
function render.SetViewPort() end
function render.Clear() end
function render.Capture() end
function render.SetStencilCompareFunction() end
function render.SetShadowsDisabled() end
function render.DrawScreenQuad() end
function render.Spin() end
function render.DrawBox() end
function render.SetShadowColor() end
function render.GetSuperFPTex() end
function render.GetFogColor() end
function render.MaterialOverride() end
function render.GetScreenEffectTexture() end
function render.SetShadowDistance() end
function render.SetMaterial() end
function render.GetSmallTex1() end
function render.SetStencilPassOperation() end
function render.FogStart() end
function render.PushFilterMag() end
function render.FogMode() end
function render.BrushMaterialOverride() end
function render.OverrideAlphaWriteEnable() end
function render.GetPowerOfTwoTexture() end
function render.SupportsPixelShaders_1_4() end
function render.SetColorModulation() end
function render.GetAmbientLightColor() end
function render.SupportsVertexShaders_2_0() end
function render.ClearBuffersObeyStencil() end
function render.GetToneMappingScaleLinear() end
function render.DrawQuadEasy() end
function render.OverrideColorWriteEnable() end
function render.GetFogDistances() end
function render.SetStencilZFailOperation() end
function render.SetLocalModelLights() end
function render.PopFilterMag() end
function render.ModelMaterialOverride() end
function render.RenderView() end
function render.EnableClipping() end
function render.SetScissorRect() end
function render.SupportsPixelShaders_2_0() end
function render.ComputeDynamicLighting() end
function render.UpdateRefractTexture() end
function render.SetWriteDepthToDestAlpha() end
function render.DrawSprite() end
function render.ResetModelLighting() end
function render.CullMode() end
function render.GetSurfaceColor() end
function render.UpdateFullScreenDepthTexture() end
function render.SetFogZ() end
function render.PushFilterMin() end
function render.GetMorphTex1() end
function render.GetMoBlurTex0() end
function render.GetMorphTex0() end
function render.SetStencilEnable() end
function render.OverrideDepthEnable() end
function render.DrawWireframeBox() end
function render.SetRenderTargetEx() end
function render.SetToneMappingScaleLinear() end
function render.ReadPixel() end
function render.PopCustomClipPlane() end
function render.DepthRange() end
function render.GetRefractTexture() end
function render.SetAmbientLight() end
function render.GetFogMode() end
function render.DrawBeam() end
function render.AddBeam() end
function render.PerformFullScreenStencilOperation() end
function render.UpdateScreenEffectTexture() end
function render.UpdatePowerOfTwoTexture() end
function render.GetSmallTex0() end
function render.ResetToneMappingScale() end
function render.GetBlend() end
function render.ComputeLighting() end
function render.MaterialOverrideByIndex() end
function render.MaxTextureWidth() end
function render.PopRenderTarget() end
function render.ClearStencil() end
function render.GetResolvedFullFrameDepth() end
function render.ClearDepth() end
function render.EndBeam() end
function render.DrawLine() end
function render.StartBeam() end
function render.SetRenderTarget() end
function render.GetColorModulation() end
function render.GetBloomTex1() end
function render.SetStencilWriteMask() end
function render.SetModelLighting() end
function render.SetStencilFailOperation() end
function render.SetStencilReferenceValue() end
function render.RenderHUD() end
function render.DrawQuad() end
function render.CopyRenderTargetToTexture() end
function render.ClearStencilBufferRectangle() end
function render.PushCustomClipPlane() end
function render.SetLightmapTexture() end
function render.FogEnd() end
function render.SetLightingOrigin() end
function render.FogColor() end
function render.DrawSphere() end
function render.GetRenderTarget() end
function render.SetGoalToneMappingScale() end
function render.GetBloomTex0() end
function render.MaxTextureHeight() end
function render.CapturePixels() end
function render.GetMoBlurTex1() end
function render.PushFlashlightMode() end
function render.PopFlashlightMode() end
function render.SetShadowDirection() end
function render.PushRenderTarget() end
function render.GetLightColor() end
function render.TurnOnToneMapping() end
function render.PopFilterMin() end

return render