local util = {}

function util.IsModelLoaded() end
function util.SteamIDTo64() end
function util.GetModelInfo() end
function util.BlastDamage() end
function util.JSONToTable() end
function util.GetSurfaceIndex() end
function util.SteamIDFrom64() end
function util.KeyValuesToTablePreserveOrder() end
function util.IsSkyboxVisibleFromPoint() end
function util.DecalEx() end
function util.TableToJSON() end
function util.IntersectRayWithOBB() end
function util.TableToKeyValues() end
function util.ParticleTracerEx() end
function util.RelativePathToFull() end
function util.Base64Encode() end
function util.AimVector() end
function util.GetSurfacePropName() end
function util.TraceLine() end
function util.IsValidProp() end
function util.IntersectRayWithPlane() end
function util.SharedRandom() end
function util.TraceEntityHull() end
function util.NetworkStringToID() end
function util.Decal() end
function util.IsValidRagdoll() end
function util.TimerCycle() end
function util.KeyValuesToTable() end
function util.DistanceToLine() end
function util.ScreenShake() end
function util.IsValidModel() end
function util.PrecacheModel() end
function util.PrecacheSound() end
function util.DecalMaterial() end
function util.GetSunInfo() end
function util.Compress() end
function util.PointContents() end
function util.BlastDamageInfo() end
function util.ParticleTracer() end
function util.GetPixelVisibleHandle() end
function util.PixelVisible() end
function util.TraceHull() end
function util.CRC() end
function util.TraceEntity() end
function util.NetworkIDToString() end
function util.Effect() end
function util.Decompress() end

return util