return {
	alGenEffects = "LPALGENEFFECTS",
	alDeleteEffects = "LPALDELETEEFFECTS",
	alIsEffect = "LPALISEFFECT",
	alEffecti = "LPALEFFECTI",
	alEffectiv = "LPALEFFECTIV",
	alEffectf = "LPALEFFECTF",
	alEffectfv = "LPALEFFECTFV",
	alGetEffecti = "LPALGETEFFECTI",
	alGetEffectiv = "LPALGETEFFECTIV",
	alGetEffectf = "LPALGETEFFECTF",
	alGetEffectfv = "LPALGETEFFECTFV",

	alGenFilters = "LPALGENFILTERS",
	alDeleteFilters = "LPALDELETEFILTERS",
	alIsFilter = "LPALISFILTER",
	alFilteri = "LPALFILTERI",
	alFilteriv = "LPALFILTERIV",
	alFilterf = "LPALFILTERF",
	alFilterfv = "LPALFILTERFV",
	alGetFilteri = "LPALGETFILTERI",
	alGetFilteriv = "LPALGETFILTERIV",
	alGetFilterf = "LPALGETFILTERF",
	alGetFilterfv = "LPALGETFILTERFV",

	alGenAuxiliaryEffectSlots = "LPALGENAUXILIARYEFFECTSLOTS",
	alDeleteAuxiliaryEffectSlots = "LPALDELETEAUXILIARYEFFECTSLOTS",
	alIsAuxiliaryEffectSlot = "LPALISAUXILIARYEFFECTSLOT",
	alAuxiliaryEffectSloti = "LPALAUXILIARYEFFECTSLOTI",
	alAuxiliaryEffectSlotiv = "LPALAUXILIARYEFFECTSLOTIV",
	alAuxiliaryEffectSlotf = "LPALAUXILIARYEFFECTSLOTF",
	alAuxiliaryEffectSlotfv = "LPALAUXILIARYEFFECTSLOTFV",
	alGetAuxiliaryEffectSloti = "LPALGETAUXILIARYEFFECTSLOTI",
	alGetAuxiliaryEffectSlotiv = "LPALGETAUXILIARYEFFECTSLOTIV",
	alGetAuxiliaryEffectSlotf = "LPALGETAUXILIARYEFFECTSLOTF",
	alGetAuxiliaryEffectSlotfv = "LPALGETAUXILIARYEFFECTSLOTFV",
	
	alBufferSamplesSOFT = "LPALBUFFERSAMPLESSOFT",
	alIsBufferFormatSupportedSOFT = "LPALISBUFFERFORMATSUPPORTEDSOFT",

	alSourcedSOFT = "LPALSOURCEDSOFT",
	alSource3dSOFT = "LPALSOURCE3DSOFT",
	alSourcedvSOFT = "LPALSOURCEDVSOFT",
	alGetSourcedSOFT = "LPALGETSOURCEDSOFT",
	alGetSource3dSOFT = "LPALGETSOURCE3DSOFT",
	alGetSourcedvSOFT = "LPALGETSOURCEDVSOFT",

	alBufferSamplesSOFT = "LPALBUFFERSAMPLESSOFT",
	alIsBufferFormatSupportedSOFT = "LPALISBUFFERFORMATSUPPORTEDSOFT",
		
	alGetInteger64SOFT = "ALint64SOFT(*)(ALenum pname)",
	alGetInteger64vSOFT = "void(*)(ALenum pname, ALint64SOFT *values)",
	
	alMidiPlaySOFT = "void(*)(void)",
	alMidiPauseSOFT = "void(*)(void)",
	alMidiStopSOFT = "void(*)(void)", 
	alMidiResetSOFT = "void(*)(void)",
	
	alMidiGainSOFT = "void(*)(ALfloat value)",
	
	alIsSoundfontSOFT = "ALboolean(*)(const char *filename)",
	alMidiSoundfontSOFT = "void(*)(ALuint id)",
	alMidiSoundfontvSOFT = "void(*)(ALsizei count, const ALuint *ids)",
	
	alMidiEventSOFT = "void(*)(ALuint64SOFT time, ALenum event, ALsizei channel, ALsizei param1, ALsizei param2)", 
	alMidiSysExSOFT = "void(*)(ALuint64SOFT time, const ALbyte *data, ALsizei size)",	
	alLoadSoundfontSOFT = "void(*)(ALuint id, size_t(*cb)(ALvoid*, size_t, ALvoid*), ALvoid *user)",
}