local icons = {
	copy = "textures/silkicons/page_white_text.png",
	uniqueid = "textures/silkicons/vcard.png",
	paste = "textures/silkicons/paste_plain.png",
	clone = "textures/silkicons/page_copy.png",
	new = "textures/silkicons/add.png",
	autoload = "textures/silkicons/transmit_go.png",
	url = "textures/silkicons/server_go.png",
	outfit = "textures/silkicons/group.png",
	clear = "textures/silkicons/cross.png",
	language = "textures/silkicons/user_comment.png",
	font = "textures/silkicons/text_smallcaps.png",
	load = "textures/silkicons/folder.png",
	save = "textures/silkicons/disk.png",
	exit = "textures/silkicons/cancel.png",
	wear = "textures/silkicons/transmit.png",
	help = "textures/silkicons/information.png",
	edit = "textures/silkicons/table_edit.png",
	revert = "textures/silkicons/table_delete.png",
	about = "textures/silkicons/star.png",
	appearance = "textures/silkicons/paintcan.png",
	orientation = "textures/silkicons/shape_handles.png",

	text = "textures/silkicons/text_align_center.png",
	bone = "widgets/bone_small.png",
	clip = "textures/silkicons/cut.png",
	light = "textures/silkicons/lightbulb.png",
	sprite = "textures/silkicons/layers.png",
	bone = "textures/silkicons/connect.png",
	effect = "textures/silkicons/wand.png",
	model = "textures/silkicons/shape_square.png",
	animation = "textures/silkicons/eye.png",
	holdtype = "textures/silkicons/user_edit.png",
	entity = "textures/silkicons/brick.png",
	group = "textures/silkicons/world.png",
	trail = "textures/silkicons/arrow_undo.png",
	event = "textures/silkicons/clock.png",
	sunbeams = "textures/silkicons/weather_sun.png",
	jiggle = "textures/silkicons/chart_line.png",
	sound = "textures/silkicons/sound.png",
	command = "textures/silkicons/application_xp_terminal.png",
	material = "textures/silkicons/paintcan.png",
	proxy = "textures/silkicons/calculator.png",
	particles = "textures/silkicons/water.png",
	woohoo = "textures/silkicons/webcam_delete.png",
	halo = "textures/silkicons/shading.png",
	poseparameter = "textures/silkicons/disconnect.png",
	fog = "textures/silkicons/weather_clouds.png",
	physics = "textures/silkicons/shape_handles.png",
	beam = "textures/silkicons/vector.png",
	projectile = "textures/silkicons/bomb.png",
	shake = "textures/silkicons/transmit.png",
	ogg = "textures/silkicons/music.png",
	webaudio = "textures/silkicons/sound_add.png",
	script = "textures/silkicons/page_white_gear.png",
	info = "textures/silkicons/help.png",
	bodygroup = "textures/silkicons/user.png",
	camera = "textures/silkicons/camera.png",
	custom_animation = "textures/silkicons/film.png",
}


for k,v in pairs(vfs.Find("textures/silkicons/")) do
	local name = v:sub(0, -5)
	icons[name] = "textures/silkicons/" .. v
end

return icons